From openjdk:11
EXPOSE 9000
copy ./target/Ecommerce_User_LogIn_Module-1-0.0.1-SNAPSHOT.jar Ecommerce_User_LogIn_Module-1-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","Ecommerce_User_LogIn_Module-1-0.0.1-SNAPSHOT.jar"]